name: Build P2 Update Site

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify -Pflat-repo
      - name: Upload p2 update site
        uses: actions/upload-artifact@v2
        with:
          name: m2eclipse-tycho
          path: org.sonatype.tycho.repository/target/repository/*

      - name: Upload flat p2 update site
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            org.sonatype.tycho.repository/target/flat-repository/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            org.sonatype.tycho.repository/target/flat-repository/*